defmodule Wik.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "user"
      add :email, :citext
      add :tz, :text
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :type, :text, null: false
      add :status, :text, null: false, default: "new"
      add :subject, :text, null: false
      add :body, :text, null: false
      add :admin_notes, :text
      add :app_path, :text, null: false
      add :handled_at, :utc_datetime_usec

      add :submitted_by_id,
          references(:users,
            column: :id,
            name: "tickets_submitted_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :slug, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :space_id, :uuid, null: false
    end

    create table(:taggings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :taggable_type, :text, null: false
      add :taggable_id, :uuid, null: false
      add :dimensions, :map, null: false
      add :description, :text
      add :space_id, :uuid, null: false
      add :tag_id, :uuid, null: false
      add :tagged_by_membership_id, :uuid, null: false
    end

    create table(:tag_edges, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :space_id, :uuid, null: false
      add :parent_tag_id, :uuid, null: false
      add :child_tag_id, :uuid, null: false
    end

    create table(:spaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:tags) do
      modify :space_id,
             references(:spaces,
               column: :id,
               name: "tags_space_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:tags, [:space_id, :id], name: "tags_unique_space_scoped_id_index")

    create unique_index(:tags, [:space_id, :slug], name: "tags_unique_space_slug_index")

    alter table(:tag_edges) do
      modify :space_id,
             references(:spaces,
               column: :id,
               name: "tag_edges_space_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :parent_tag_id,
             references(:tags,
               column: :id,
               with: [space_id: :space_id],
               name: "tag_edges_parent_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :child_tag_id,
             references(:tags,
               column: :id,
               with: [space_id: :space_id],
               name: "tag_edges_child_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:tag_edges, [:space_id, :parent_tag_id, :child_tag_id],
             name: "tag_edges_unique_space_parent_child_index"
           )

    alter table(:spaces) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text

      add :author_id,
          references(:users,
            column: :id,
            name: "spaces_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:spaces, [:slug], name: "spaces_unique_slug_index")

    create table(:profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :membership_id, :uuid, null: false
    end

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :title, :text, null: false
      add :body, :text, null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "posts_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "posts_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :space_id,
          references(:spaces,
            column: :id,
            name: "pages_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "pages_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:page_trees, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :nodes, {:array, :map}, null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "page_trees_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:page_trees, [:space_id], name: "page_trees_unique_space_page_tree_index")

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :space_id,
          references(:spaces,
            column: :id,
            name: "memberships_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :type, :text, null: false, default: "member"
      add :username, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:memberships, [:space_id, :user_id],
             name: "memberships_unique_membership_index"
           )

    create unique_index(:memberships, [:id, :space_id],
             name: "memberships_unique_space_scoped_id_index"
           )

    alter table(:taggings) do
      modify :taggable_id,
             references(:memberships,
               column: :id,
               with: [space_id: :space_id],
               name: "taggings_taggable_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :space_id,
             references(:spaces,
               column: :id,
               name: "taggings_space_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :tag_id,
             references(:tags,
               column: :id,
               with: [space_id: :space_id],
               name: "taggings_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :tagged_by_membership_id,
             references(:memberships,
               column: :id,
               with: [space_id: :space_id],
               name: "taggings_tagged_by_membership_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(
             :taggings,
             [:space_id, :taggable_type, :taggable_id, :tagged_by_membership_id, :tag_id],
             name: "taggings_unique_space_target_author_tag_index"
           )

    alter table(:profiles) do
      modify :membership_id,
             references(:memberships,
               column: :id,
               name: "profiles_membership_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:profiles, [:membership_id],
             name: "profiles_unique_membership_profile_index"
           )

    create unique_index(:memberships, [:space_id, :username],
             name: "memberships_unique_space_username_index"
           )

    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :all_day, :boolean, null: false, default: false
      add :description, :text, null: false
      add :ends_at, :utc_datetime
      add :location, :text, null: false
      add :provenance_policy, :text, null: false, default: "visible"
      add :relay_policy, :text, null: false, default: "internal_only"
      add :starts_at, :utc_datetime, null: false
      add :tz, :text, null: false
      add :status, :text, null: false, default: "published"
      add :title, :text, null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "events_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "events_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:event_publications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :publication_type, :text, null: false
      add :relay_note, :text

      add :event_id,
          references(:events,
            column: :id,
            name: "event_publications_event_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :target_space_id,
          references(:spaces,
            column: :id,
            name: "event_publications_target_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :published_by_id,
          references(:users,
            column: :id,
            name: "event_publications_published_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:event_publications, [:target_space_id, :event_id],
             name: "event_publications_unique_event_publication_index"
           )

    create table(:blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :type, :text, null: false
      add :data, :map, null: false, default: %{}

      add :author_id,
          references(:users,
            column: :id,
            name: "blocks_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :owner_space_id,
          references(:spaces,
            column: :id,
            name: "blocks_owner_space_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "blocks_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:block_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :block_type, :text, null: false
      add :diff_data, :map
      add :revision, :bigint, null: false
      add :snapshot_text, :text
      add :storage_kind, :text, null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "block_versions_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :block_id,
          references(:blocks,
            column: :id,
            name: "block_versions_block_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:block_versions, [:block_id, :revision],
             name: "block_versions_unique_block_revision_index"
           )

    create table(:block_placements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :attachable_id, :uuid, null: false
      add :attachable_type, :text, null: false
      add :order_key, :text, null: false
      add :area, :text

      add :block_id,
          references(:blocks,
            column: :id,
            name: "block_placements_block_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "block_placements_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:block_placements, [:attachable_type, :attachable_id, :order_key],
             name: "block_placements_unique_attachable_order_key_index"
           )

    create table(:access_telegram_bot_updates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :payload, :map, null: false
      add :summary, :map, null: false
      add :update_id, :bigint, null: false
    end

    create table(:access_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :claimed_at, :utc_datetime_usec
      add :metadata, :map, null: false, default: %{}
      add :provider, :text, null: false
      add :provider_source_id, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :title, :text, null: false

      add :claimed_by_user_id,
          references(:users,
            column: :id,
            name: "access_sources_claimed_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :space_id,
          references(:spaces,
            column: :id,
            name: "access_sources_space_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:access_sources, [:provider, :provider_source_id],
             name: "access_sources_unique_provider_source_index"
           )

    create table(:access_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :last_verified_at, :utc_datetime_usec, null: false
      add :status, :text, null: false, default: "active"
      add :external_identity_id, :uuid, null: false
      add :source_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create table(:access_external_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:access_grants) do
      modify :external_identity_id,
             references(:access_external_identities,
               column: :id,
               name: "access_grants_external_identity_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :source_id,
             references(:access_sources,
               column: :id,
               name: "access_grants_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "access_grants_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:access_grants, [:source_id, :user_id],
             name: "access_grants_unique_source_user_index"
           )

    alter table(:access_external_identities) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :avatar_url, :text
      add :display_name, :text
      add :metadata, :map, null: false, default: %{}
      add :provider, :text, null: false
      add :provider_user_id, :text, null: false
      add :username, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "access_external_identities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:access_external_identities, [:provider, :provider_user_id],
             name: "access_external_identities_unique_provider_user_index"
           )

    create constraint(:tag_edges, :tag_edges_no_self_reference,
             check: """
               parent_tag_id <> child_tag_id
             """
           )
  end

  def down do
    drop_if_exists constraint(:tag_edges, :tag_edges_no_self_reference)

    drop_if_exists unique_index(:access_external_identities, [:provider, :provider_user_id],
                     name: "access_external_identities_unique_provider_user_index"
                   )

    drop constraint(:access_external_identities, "access_external_identities_user_id_fkey")

    alter table(:access_external_identities) do
      remove :user_id
      remove :username
      remove :provider_user_id
      remove :provider
      remove :metadata
      remove :display_name
      remove :avatar_url
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:access_grants, [:source_id, :user_id],
                     name: "access_grants_unique_source_user_index"
                   )

    drop constraint(:access_grants, "access_grants_external_identity_id_fkey")

    drop constraint(:access_grants, "access_grants_source_id_fkey")

    drop constraint(:access_grants, "access_grants_user_id_fkey")

    alter table(:access_grants) do
      modify :user_id, :uuid
      modify :source_id, :uuid
      modify :external_identity_id, :uuid
    end

    drop table(:access_external_identities)

    drop table(:access_grants)

    drop_if_exists unique_index(:access_sources, [:provider, :provider_source_id],
                     name: "access_sources_unique_provider_source_index"
                   )

    drop constraint(:access_sources, "access_sources_claimed_by_user_id_fkey")

    drop constraint(:access_sources, "access_sources_space_id_fkey")

    drop table(:access_sources)

    drop table(:access_telegram_bot_updates)

    drop_if_exists unique_index(:block_placements, [:attachable_type, :attachable_id, :order_key],
                     name: "block_placements_unique_attachable_order_key_index"
                   )

    drop constraint(:block_placements, "block_placements_block_id_fkey")

    drop constraint(:block_placements, "block_placements_space_id_fkey")

    drop table(:block_placements)

    drop_if_exists unique_index(:block_versions, [:block_id, :revision],
                     name: "block_versions_unique_block_revision_index"
                   )

    drop constraint(:block_versions, "block_versions_author_id_fkey")

    drop constraint(:block_versions, "block_versions_block_id_fkey")

    drop table(:block_versions)

    drop constraint(:blocks, "blocks_author_id_fkey")

    drop constraint(:blocks, "blocks_owner_space_id_fkey")

    drop constraint(:blocks, "blocks_owner_user_id_fkey")

    drop table(:blocks)

    drop_if_exists unique_index(:event_publications, [:target_space_id, :event_id],
                     name: "event_publications_unique_event_publication_index"
                   )

    drop constraint(:event_publications, "event_publications_event_id_fkey")

    drop constraint(:event_publications, "event_publications_target_space_id_fkey")

    drop constraint(:event_publications, "event_publications_published_by_id_fkey")

    drop table(:event_publications)

    drop constraint(:events, "events_author_id_fkey")

    drop constraint(:events, "events_space_id_fkey")

    drop table(:events)

    drop_if_exists unique_index(:memberships, [:space_id, :username],
                     name: "memberships_unique_space_username_index"
                   )

    drop_if_exists unique_index(:profiles, [:membership_id],
                     name: "profiles_unique_membership_profile_index"
                   )

    drop constraint(:profiles, "profiles_membership_id_fkey")

    alter table(:profiles) do
      modify :membership_id, :uuid
    end

    drop_if_exists unique_index(
                     :taggings,
                     [:space_id, :taggable_type, :taggable_id, :tagged_by_membership_id, :tag_id],
                     name: "taggings_unique_space_target_author_tag_index"
                   )

    drop constraint(:taggings, "taggings_taggable_id_fkey")

    drop constraint(:taggings, "taggings_space_id_fkey")

    drop constraint(:taggings, "taggings_tag_id_fkey")

    drop constraint(:taggings, "taggings_tagged_by_membership_id_fkey")

    alter table(:taggings) do
      modify :tagged_by_membership_id, :uuid
      modify :tag_id, :uuid
      modify :space_id, :uuid
      modify :taggable_id, :uuid
    end

    drop_if_exists unique_index(:memberships, [:id, :space_id],
                     name: "memberships_unique_space_scoped_id_index"
                   )

    drop_if_exists unique_index(:memberships, [:space_id, :user_id],
                     name: "memberships_unique_membership_index"
                   )

    drop constraint(:memberships, "memberships_space_id_fkey")

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop table(:memberships)

    drop_if_exists unique_index(:page_trees, [:space_id],
                     name: "page_trees_unique_space_page_tree_index"
                   )

    drop constraint(:page_trees, "page_trees_space_id_fkey")

    drop table(:page_trees)

    drop constraint(:pages, "pages_space_id_fkey")

    drop constraint(:pages, "pages_author_id_fkey")

    drop table(:pages)

    drop constraint(:posts, "posts_space_id_fkey")

    drop constraint(:posts, "posts_author_id_fkey")

    drop table(:posts)

    drop table(:profiles)

    drop_if_exists unique_index(:spaces, [:slug], name: "spaces_unique_slug_index")

    drop constraint(:spaces, "spaces_author_id_fkey")

    alter table(:spaces) do
      remove :author_id
      remove :description
      remove :slug
      remove :name
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:tag_edges, [:space_id, :parent_tag_id, :child_tag_id],
                     name: "tag_edges_unique_space_parent_child_index"
                   )

    drop constraint(:tag_edges, "tag_edges_space_id_fkey")

    drop constraint(:tag_edges, "tag_edges_parent_tag_id_fkey")

    drop constraint(:tag_edges, "tag_edges_child_tag_id_fkey")

    alter table(:tag_edges) do
      modify :child_tag_id, :uuid
      modify :parent_tag_id, :uuid
      modify :space_id, :uuid
    end

    drop_if_exists unique_index(:tags, [:space_id, :slug], name: "tags_unique_space_slug_index")

    drop_if_exists unique_index(:tags, [:space_id, :id],
                     name: "tags_unique_space_scoped_id_index"
                   )

    drop constraint(:tags, "tags_space_id_fkey")

    alter table(:tags) do
      modify :space_id, :uuid
    end

    drop table(:spaces)

    drop table(:tag_edges)

    drop table(:taggings)

    drop table(:tags)

    drop constraint(:tickets, "tickets_submitted_by_id_fkey")

    drop table(:tickets)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
