defmodule Qblog.Repo.Migrations.AddAccessSources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:access_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :claimed_at, :utc_datetime_usec
      add :metadata, :map, null: false, default: %{}
      add :provider, :text, null: false
      add :provider_source_id, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :title, :text, null: false

      add :claimed_by_user_id,
          references(:users,
            column: :id,
            name: "access_sources_claimed_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :group_id,
          references(:groups,
            column: :id,
            name: "access_sources_group_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:access_sources, [:provider, :provider_source_id],
             name: "access_sources_unique_provider_source_index"
           )

    create table(:access_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :last_verified_at, :utc_datetime_usec, null: false
      add :status, :text, null: false, default: "active"
      add :external_identity_id, :uuid, null: false
      add :source_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create table(:access_external_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:access_grants) do
      modify :external_identity_id,
             references(:access_external_identities,
               column: :id,
               name: "access_grants_external_identity_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :source_id,
             references(:access_sources,
               column: :id,
               name: "access_grants_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "access_grants_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:access_grants, [:source_id, :user_id],
             name: "access_grants_unique_source_user_index"
           )

    alter table(:access_external_identities) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :avatar_url, :text
      add :display_name, :text
      add :metadata, :map, null: false, default: %{}
      add :provider, :text, null: false
      add :provider_user_id, :text, null: false
      add :username, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "access_external_identities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:access_external_identities, [:provider, :provider_user_id],
             name: "access_external_identities_unique_provider_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:access_external_identities, [:provider, :provider_user_id],
                     name: "access_external_identities_unique_provider_user_index"
                   )

    drop constraint(:access_external_identities, "access_external_identities_user_id_fkey")

    alter table(:access_external_identities) do
      remove :user_id
      remove :username
      remove :provider_user_id
      remove :provider
      remove :metadata
      remove :display_name
      remove :avatar_url
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:access_grants, [:source_id, :user_id],
                     name: "access_grants_unique_source_user_index"
                   )

    drop constraint(:access_grants, "access_grants_external_identity_id_fkey")

    drop constraint(:access_grants, "access_grants_source_id_fkey")

    drop constraint(:access_grants, "access_grants_user_id_fkey")

    alter table(:access_grants) do
      modify :user_id, :uuid
      modify :source_id, :uuid
      modify :external_identity_id, :uuid
    end

    drop table(:access_external_identities)

    drop table(:access_grants)

    drop_if_exists unique_index(:access_sources, [:provider, :provider_source_id],
                     name: "access_sources_unique_provider_source_index"
                   )

    drop constraint(:access_sources, "access_sources_claimed_by_user_id_fkey")

    drop constraint(:access_sources, "access_sources_group_id_fkey")

    drop table(:access_sources)
  end
end
