defmodule Qblog.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("group_user_relations", "group_user_relations_pkey")

    alter table(:group_user_relations) do
      modify :user_id, :uuid, primary_key: false
      modify :group_id, :uuid, primary_key: false
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end
  end

  def down do
    drop constraint("group_user_relations", "group_user_relations_pkey")

    alter table(:group_user_relations) do
      remove :id
      modify :group_id, :uuid, primary_key: true
      modify :user_id, :uuid, primary_key: true
    end
  end
end
