defmodule Wik.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:external_calendar_subscriptions) do
      add :custom_name, :text
    end
  end

  def down do
    alter table(:external_calendar_subscriptions) do
      remove :custom_name
    end
  end
end
