defmodule Wik.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:external_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :external_uid, :text, null: false
      add :external_recurrence_id, :text
      add :external_occurrence_key, :text, null: false
      add :title, :text, null: false
      add :starts_at, :utc_datetime_usec, null: false
      add :ends_at, :utc_datetime_usec, null: false
      add :all_day, :boolean, null: false, default: false
      add :tz, :text, null: false
      add :status, :text, null: false, default: "published"
      add :location, :text
      add :description, :text
      add :event_url, :text
      add :calendar_name, :text
      add :last_seen_at, :utc_datetime_usec, null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "external_events_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :subscription_id,
          references(:external_calendar_subscriptions,
            column: :id,
            name: "external_events_subscription_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(
             :external_events,
             [:space_id, :subscription_id, :external_uid, :external_occurrence_key],
             name: "external_events_subscription_occurrence_idx"
           )

    alter table(:external_calendar_subscriptions) do
      add :cached_calendar_name, :text
    end
  end

  def down do
    alter table(:external_calendar_subscriptions) do
      remove :cached_calendar_name
    end

    drop_if_exists unique_index(
                     :external_events,
                     [:space_id, :subscription_id, :external_uid, :external_occurrence_key],
                     name: "external_events_subscription_occurrence_idx"
                   )

    drop constraint(:external_events, "external_events_space_id_fkey")

    drop constraint(:external_events, "external_events_subscription_id_fkey")

    drop table(:external_events)
  end
end
