defmodule Wik.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:tag_edges, :tag_edges_no_self_reference,
             check: """
               parent_tag_id <> child_tag_id
             """
           )
  end

  def down do
    drop_if_exists constraint(:tag_edges, :tag_edges_no_self_reference)
  end
end
