defmodule Wik.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_user_relations) do
      add :username, :text
    end

    create unique_index(:group_user_relations, [:group_id, :username],
             name: "group_user_relations_unique_group_username_index"
           )
  end

  def down do
    drop_if_exists unique_index(:group_user_relations, [:group_id, :username],
                     name: "group_user_relations_unique_group_username_index"
                   )

    alter table(:group_user_relations) do
      remove :username
    end
  end
end
