defmodule Wik.Repo.Migrations.MigrateResources17 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:taggings, "taggings_taggable_id_fkey")

    alter table(:taggings) do
      modify :taggable_id, :uuid
    end

    create index(:taggings, [:space_id, :taggable_id])
  end

  def down do
    drop_if_exists index(:taggings, [:space_id, :taggable_id])

    alter table(:taggings) do
      modify :taggable_id,
             references(:memberships,
               column: :id,
               name: "taggings_taggable_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
