defmodule Qblog.Repo.Migrations.Initialize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "user"
      add :email, :citext, null: false
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :title, :text, null: false
      add :body, :text, null: false
      add :group_id, :uuid, null: false
      add :author_id, :uuid, null: false
    end

    create table(:pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :title, :text, null: false
      add :slug, :text, null: false
      add :group_id, :uuid, null: false
      add :author_id, :uuid, null: false
    end

    create table(:page_trees, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :nodes, {:array, :map}, null: false
      add :group_id, :uuid, null: false
    end

    create table(:groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:posts) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "posts_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :author_id,
             references(:users,
               column: :id,
               name: "posts_author_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:pages) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "pages_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :author_id,
             references(:users,
               column: :id,
               name: "pages_author_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:page_trees) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "page_trees_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:page_trees, [:group_id], name: "page_trees_unique_group_page_tree_index")

    alter table(:groups) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false

      add :owner_id,
          references(:users,
            column: :id,
            name: "groups_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:groups, [:name], name: "groups_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:groups, [:name], name: "groups_unique_name_index")

    drop constraint(:groups, "groups_owner_id_fkey")

    alter table(:groups) do
      remove :owner_id
      remove :name
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:page_trees, [:group_id],
                     name: "page_trees_unique_group_page_tree_index"
                   )

    drop constraint(:page_trees, "page_trees_group_id_fkey")

    alter table(:page_trees) do
      modify :group_id, :uuid
    end

    drop constraint(:pages, "pages_group_id_fkey")

    drop constraint(:pages, "pages_author_id_fkey")

    alter table(:pages) do
      modify :author_id, :uuid
      modify :group_id, :uuid
    end

    drop constraint(:posts, "posts_group_id_fkey")

    drop constraint(:posts, "posts_author_id_fkey")

    alter table(:posts) do
      modify :author_id, :uuid
      modify :group_id, :uuid
    end

    drop table(:groups)

    drop table(:page_trees)

    drop table(:pages)

    drop table(:posts)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
