defmodule Qblog.Repo.Migrations.AddBlockPlacementGroupId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:block_placements) do
      add :group_id,
          references(:groups,
            column: :id,
            name: "block_placements_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:block_placements, "block_placements_group_id_fkey")

    alter table(:block_placements) do
      remove :group_id
    end
  end
end
