defmodule Qblog.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:groups, [:name], name: "groups_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:groups, [:name], name: "groups_unique_name_index")
  end
end