defmodule Wik.Repo.Migrations.AddExternalCalendarTopicMatching do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:external_calendar_topic_rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :aliases, {:array, :text}, null: false, default: []
      add :enabled, :boolean, null: false, default: true
      add :match_description, :boolean, null: false, default: true
      add :match_title, :boolean, null: false, default: true

      add :space_id,
          references(:spaces,
            column: :id,
            name: "external_calendar_topic_rules_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :subscription_id, :uuid, null: false
      add :tag_id, :uuid, null: false
    end

    alter table(:external_calendar_subscriptions) do
      add :automatic_topic_matching, :boolean, null: false, default: true
    end

    create unique_index(:external_calendar_subscriptions, [:space_id, :id],
             name: "external_calendar_subscriptions_unique_space_scoped_id_index"
           )

    alter table(:external_calendar_topic_rules) do
      modify :subscription_id,
             references(:external_calendar_subscriptions,
               column: :id,
               with: [space_id: :space_id],
               name: "external_calendar_topic_rules_subscription_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :tag_id,
             references(:tags,
               column: :id,
               with: [space_id: :space_id],
               name: "external_calendar_topic_rules_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:external_calendar_topic_rules, [:space_id, :subscription_id, :tag_id],
             name: "ext_cal_topic_rules_space_sub_tag_idx"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :external_calendar_topic_rules,
                     [:space_id, :subscription_id, :tag_id],
                     name: "ext_cal_topic_rules_space_sub_tag_idx"
                   )

    drop constraint(
           :external_calendar_topic_rules,
           "external_calendar_topic_rules_subscription_id_fkey"
         )

    drop constraint(:external_calendar_topic_rules, "external_calendar_topic_rules_tag_id_fkey")

    alter table(:external_calendar_topic_rules) do
      modify :tag_id, :uuid
      modify :subscription_id, :uuid
    end

    drop_if_exists unique_index(:external_calendar_subscriptions, [:space_id, :id],
                     name: "external_calendar_subscriptions_unique_space_scoped_id_index"
                   )

    alter table(:external_calendar_subscriptions) do
      remove :automatic_topic_matching
    end

    drop constraint(:external_calendar_topic_rules, "external_calendar_topic_rules_space_id_fkey")

    drop table(:external_calendar_topic_rules)
  end
end
