defmodule Qblog.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :email, :citext, null: false
      add :role, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:posts, primary_key: false) do
      add :author_id, references(:users, column: :id, name: "posts_author_id_fkey", type: :uuid),
        null: false

      add :group_id, references(:groups, column: :id, name: "posts_group_id_fkey", type: :uuid),
        null: false

      add :body, :text, null: false
      add :title, :text, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:groups, primary_key: false) do
      add :owner_id, references(:users, column: :id, name: "groups_owner_id_fkey", type: :uuid),
        null: false

      add :name, :text, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:groups, [:name], name: "groups_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:groups, [:name], name: "groups_unique_name_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `groups` table without the `groups_owner_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:groups)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `posts` table without the `posts_group_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `posts` table without the `posts_author_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:posts)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end