defmodule Wik.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      remove :provenance_policy
    end
  end

  def down do
    alter table(:events) do
      add :provenance_policy, :text, null: false, default: "visible"
    end
  end
end
