defmodule Qblog.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:group_user_relations, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_user_relations_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "group_user_relations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:group_user_relations, [:group_id, :user_id],
             name: "group_user_relations_unique_group_user_relation_index"
           )
  end

  def down do
    drop_if_exists unique_index(:group_user_relations, [:group_id, :user_id],
                     name: "group_user_relations_unique_group_user_relation_index"
                   )

    drop constraint(:group_user_relations, "group_user_relations_group_id_fkey")

    drop constraint(:group_user_relations, "group_user_relations_user_id_fkey")

    drop table(:group_user_relations)
  end
end
