defmodule Wik.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:external_calendar_subscriptions) do
      add :cached_body, :text
      add :cached_at, :utc_datetime_usec
      add :etag, :text
      add :last_error, :text
    end
  end

  def down do
    alter table(:external_calendar_subscriptions) do
      remove :last_error
      remove :etag
      remove :cached_at
      remove :cached_body
    end
  end
end
