defmodule Qblog.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:block_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :block_type, :text, null: false
      add :diff_data, :map
      add :revision, :bigint, null: false
      add :snapshot_text, :text
      add :storage_kind, :text, null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "block_versions_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :block_id,
          references(:blocks,
            column: :id,
            name: "block_versions_block_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:block_versions, [:block_id, :revision],
             name: "block_versions_unique_block_revision_index"
           )
  end

  def down do
    drop_if_exists unique_index(:block_versions, [:block_id, :revision],
                     name: "block_versions_unique_block_revision_index"
                   )

    drop constraint(:block_versions, "block_versions_author_id_fkey")

    drop constraint(:block_versions, "block_versions_block_id_fkey")

    drop table(:block_versions)
  end
end
