defmodule Wik.Repo.Migrations.PersistentLibrary do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:library_entry_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :description, :text, null: false, default: ""
      add :entry_creation_permission, :text, null: false, default: "members"
      add :name, :text, null: false
      add :slug, :text, null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "library_entry_types_space_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:library_entry_types, [:space_id, :id],
             name: "library_entry_types_unique_space_scoped_id_index"
           )

    create unique_index(:library_entry_types, [:space_id, :slug],
             name: "library_entry_types_unique_space_slug_index"
           )

    create table(:library_fields, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :type, :text, null: false
      add :key, :text, null: false
      add :label, :text, null: false
      add :options, {:array, :text}, null: false, default: []
      add :order_key, :text, null: false
      add :required, :boolean, null: false, default: false

      add :type_id,
          references(:library_entry_types,
            column: :id,
            with: [space_id: :space_id],
            name: "library_fields_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "library_fields_space_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:library_fields, [:space_id, :id],
             name: "library_fields_unique_space_scoped_id_index"
           )

    create unique_index(:library_fields, [:space_id, :type_id, :key],
             name: "library_fields_unique_type_key_index"
           )

    create unique_index(:library_fields, [:space_id, :type_id, :order_key],
             name: "library_fields_unique_type_order_index"
           )

    create table(:library_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :automatic_topic_matching, :boolean, null: false, default: true

      add :space_id,
          references(:spaces,
            column: :id,
            name: "library_settings_space_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:library_settings, [:space_id],
             name: "library_settings_unique_space_index"
           )

    create table(:library_block_references, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :block_id,
          references(:blocks,
            column: :id,
            name: "library_block_references_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :entry_id, :uuid, null: false
      add :space_id, :uuid, null: false
    end

    create table(:library_topic_exclusions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :entry_id, :uuid, null: false
      add :space_id, :uuid, null: false
      add :tag_id, :uuid, null: false
    end

    create table(:library_topic_rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :aliases, {:array, :text}, null: false, default: []
      add :enabled, :boolean, null: false, default: true

      add :space_id,
          references(:spaces,
            column: :id,
            name: "library_topic_rules_space_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            with: [space_id: :space_id],
            name: "library_topic_rules_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:library_topic_rules, [:space_id, :tag_id],
             name: "library_topic_rules_unique_space_tag_index"
           )

    create table(:library_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :external_media_metadata, :map
      add :values, :map, null: false, default: %{}

      add :creator_id,
          references(:users,
            column: :id,
            name: "library_entries_creator_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :type_id,
          references(:library_entry_types,
            column: :id,
            with: [space_id: :space_id],
            name: "library_entries_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "library_entries_space_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:library_entries, [:space_id, :id],
             name: "library_entries_unique_space_scoped_id_index"
           )

    alter table(:library_block_references) do
      modify :entry_id,
             references(:library_entries,
               column: :id,
               with: [space_id: :space_id],
               name: "library_block_references_entry_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :space_id,
             references(:spaces,
               column: :id,
               name: "library_block_references_space_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:library_block_references, [:space_id, :block_id],
             name: "library_block_references_unique_block_index"
           )

    create unique_index(:library_block_references, [:space_id, :id],
             name: "library_block_references_unique_space_scoped_id_index"
           )

    alter table(:library_topic_exclusions) do
      modify :entry_id,
             references(:library_entries,
               column: :id,
               with: [space_id: :space_id],
               name: "library_topic_exclusions_entry_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :space_id,
             references(:spaces,
               column: :id,
               name: "library_topic_exclusions_space_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :tag_id,
             references(:tags,
               column: :id,
               with: [space_id: :space_id],
               name: "library_topic_exclusions_tag_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:library_topic_exclusions, [:space_id, :entry_id, :tag_id],
             name: "library_topic_exclusions_unique_entry_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:library_topic_exclusions, [:space_id, :entry_id, :tag_id],
                     name: "library_topic_exclusions_unique_entry_tag_index"
                   )

    drop constraint(:library_topic_exclusions, "library_topic_exclusions_entry_id_fkey")

    drop constraint(:library_topic_exclusions, "library_topic_exclusions_space_id_fkey")

    drop constraint(:library_topic_exclusions, "library_topic_exclusions_tag_id_fkey")

    alter table(:library_topic_exclusions) do
      modify :tag_id, :uuid
      modify :space_id, :uuid
      modify :entry_id, :uuid
    end

    drop_if_exists unique_index(:library_block_references, [:space_id, :id],
                     name: "library_block_references_unique_space_scoped_id_index"
                   )

    drop_if_exists unique_index(:library_block_references, [:space_id, :block_id],
                     name: "library_block_references_unique_block_index"
                   )

    drop constraint(:library_block_references, "library_block_references_entry_id_fkey")

    drop constraint(:library_block_references, "library_block_references_space_id_fkey")

    alter table(:library_block_references) do
      modify :space_id, :uuid
      modify :entry_id, :uuid
    end

    drop_if_exists unique_index(:library_entries, [:space_id, :id],
                     name: "library_entries_unique_space_scoped_id_index"
                   )

    drop constraint(:library_entries, "library_entries_creator_id_fkey")

    drop constraint(:library_entries, "library_entries_type_id_fkey")

    drop constraint(:library_entries, "library_entries_space_id_fkey")

    drop table(:library_entries)

    drop_if_exists unique_index(:library_topic_rules, [:space_id, :tag_id],
                     name: "library_topic_rules_unique_space_tag_index"
                   )

    drop constraint(:library_topic_rules, "library_topic_rules_space_id_fkey")

    drop constraint(:library_topic_rules, "library_topic_rules_tag_id_fkey")

    drop table(:library_topic_rules)

    drop table(:library_topic_exclusions)

    drop constraint(:library_block_references, "library_block_references_block_id_fkey")

    drop table(:library_block_references)

    drop_if_exists unique_index(:library_settings, [:space_id],
                     name: "library_settings_unique_space_index"
                   )

    drop constraint(:library_settings, "library_settings_space_id_fkey")

    drop table(:library_settings)

    drop_if_exists unique_index(:library_fields, [:space_id, :type_id, :order_key],
                     name: "library_fields_unique_type_order_index"
                   )

    drop_if_exists unique_index(:library_fields, [:space_id, :type_id, :key],
                     name: "library_fields_unique_type_key_index"
                   )

    drop_if_exists unique_index(:library_fields, [:space_id, :id],
                     name: "library_fields_unique_space_scoped_id_index"
                   )

    drop constraint(:library_fields, "library_fields_type_id_fkey")

    drop constraint(:library_fields, "library_fields_space_id_fkey")

    drop table(:library_fields)

    drop_if_exists unique_index(:library_entry_types, [:space_id, :slug],
                     name: "library_entry_types_unique_space_slug_index"
                   )

    drop_if_exists unique_index(:library_entry_types, [:space_id, :id],
                     name: "library_entry_types_unique_space_scoped_id_index"
                   )

    drop constraint(:library_entry_types, "library_entry_types_space_id_fkey")

    drop table(:library_entry_types)
  end
end
