defmodule Wik.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:taggings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :taggable_type, :text, null: false
      add :taggable_id, :uuid, null: false
      add :dimensions, :map, null: false
      add :description, :text

      add :group_id,
          references(:groups,
            column: :id,
            name: "taggings_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            with: [group_id: :group_id],
            name: "taggings_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :tagged_by_group_user_relation_id, :uuid, null: false
    end

    create unique_index(:group_user_relations, [:id, :group_id],
             name: "group_user_relations_unique_group_scoped_id_index"
           )

    alter table(:taggings) do
      modify :tagged_by_group_user_relation_id,
             references(:group_user_relations,
               column: :id,
               with: [group_id: :group_id],
               name: "taggings_tagged_by_group_user_relation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(
             :taggings,
             [
               :group_id,
               :taggable_type,
               :taggable_id,
               :tagged_by_group_user_relation_id,
               :tag_id
             ],
             name: "taggings_unique_group_target_author_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :taggings,
                     [
                       :group_id,
                       :taggable_type,
                       :taggable_id,
                       :tagged_by_group_user_relation_id,
                       :tag_id
                     ],
                     name: "taggings_unique_group_target_author_tag_index"
                   )

    drop constraint(:taggings, "taggings_tagged_by_group_user_relation_id_fkey")

    alter table(:taggings) do
      modify :tagged_by_group_user_relation_id, :uuid
    end

    drop_if_exists unique_index(:group_user_relations, [:id, :group_id],
                     name: "group_user_relations_unique_group_scoped_id_index"
                   )

    drop constraint(:taggings, "taggings_group_id_fkey")

    drop constraint(:taggings, "taggings_tag_id_fkey")

    drop table(:taggings)
  end
end
