defmodule Wik.Repo.Migrations.AddActivityEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:activity_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category, :text, null: false
      add :kind, :text, null: false
      add :subject_type, :text, null: false
      add :subject_id, :uuid, null: false
      add :subject_label, :text, null: false
      add :subject_path, :text
      add :actor_label, :text
      add :actor_username, :text
      add :metadata, :map, null: false, default: %{}
      add :occurrence_count, :bigint, null: false, default: 1
      add :occurred_at, :utc_datetime_usec, null: false
      add :collapse_key, :text

      add :space_id,
          references(:spaces,
            column: :id,
            name: "activity_entries_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :actor_membership_id,
          references(:memberships,
            column: :id,
            name: "activity_entries_actor_membership_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:activity_entries, [:space_id, :collapse_key, :occurred_at])

    create index(:activity_entries, [:space_id, :category, :occurred_at])

    create index(:activity_entries, [:space_id, :occurred_at])
  end

  def down do
    drop constraint(:activity_entries, "activity_entries_space_id_fkey")

    drop constraint(:activity_entries, "activity_entries_actor_membership_id_fkey")

    drop_if_exists index(:activity_entries, [:space_id, :occurred_at])

    drop_if_exists index(:activity_entries, [:space_id, :category, :occurred_at])

    drop_if_exists index(:activity_entries, [:space_id, :collapse_key, :occurred_at])

    drop table(:activity_entries)
  end
end
