defmodule Wik.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :slug, :text, null: false
      add :name, :text, null: false
      add :description, :text

      add :group_id,
          references(:groups,
            column: :id,
            name: "tags_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:tags, [:group_id, :id], name: "tags_unique_group_scoped_id_index")

    create unique_index(:tags, [:group_id, :slug], name: "tags_unique_group_slug_index")

    create table(:tag_edges, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "tag_edges_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :parent_tag_id,
          references(:tags,
            column: :id,
            with: [group_id: :group_id],
            name: "tag_edges_parent_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :child_tag_id,
          references(:tags,
            column: :id,
            with: [group_id: :group_id],
            name: "tag_edges_child_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:tag_edges, [:group_id, :parent_tag_id, :child_tag_id],
             name: "tag_edges_unique_group_parent_child_index"
           )
  end

  def down do
    drop_if_exists unique_index(:tag_edges, [:group_id, :parent_tag_id, :child_tag_id],
                     name: "tag_edges_unique_group_parent_child_index"
                   )

    drop constraint(:tag_edges, "tag_edges_group_id_fkey")

    drop constraint(:tag_edges, "tag_edges_parent_tag_id_fkey")

    drop constraint(:tag_edges, "tag_edges_child_tag_id_fkey")

    drop table(:tag_edges)

    drop_if_exists unique_index(:tags, [:group_id, :slug], name: "tags_unique_group_slug_index")

    drop_if_exists unique_index(:tags, [:group_id, :id],
                     name: "tags_unique_group_scoped_id_index"
                   )

    drop constraint(:tags, "tags_group_id_fkey")

    drop table(:tags)
  end
end
