defmodule Qblog.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:group_user_relations) do
      add :type, :text, null: false, default: "member"
    end
  end

  def down do
    alter table(:group_user_relations) do
      remove :type
    end
  end
end
