defmodule Qblog.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:page_trees, primary_key: false) do
      add :group_id,
          references(:groups, column: :id, name: "page_trees_group_id_fkey", type: :uuid),
          null: false

      add :nodes, {:array, :map}, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:page_trees, [:group_id, :group_id],
             name: "page_trees_unique_group_page_tree_index"
           )
  end

  def down do
    drop_if_exists unique_index(:page_trees, [:group_id, :group_id],
                     name: "page_trees_unique_group_page_tree_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `page_trees` table without the `page_trees_group_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:page_trees)
  end
end