defmodule Wik.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:external_events, "external_events_subscription_id_fkey")

    alter table(:external_events) do
      modify :subscription_id,
             references(:external_calendar_subscriptions,
               column: :id,
               name: "external_events_subscription_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:external_events, "external_events_subscription_id_fkey")

    alter table(:external_events) do
      modify :subscription_id,
             references(:external_calendar_subscriptions,
               column: :id,
               name: "external_events_subscription_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
