defmodule Wik.Repo.Migrations.AddEventTz do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :tz, :text, default: "Etc/UTC", null: false
    end

    alter table(:events) do
      modify :tz, :text, default: nil, null: false
    end
  end

  def down do
    alter table(:events) do
      remove :tz
    end
  end
end
