defmodule Wik.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:external_events) do
      add :source_missing_at, :utc_datetime_usec
    end

    alter table(:events) do
      modify :title, :text, null: true
      modify :tz, :text, null: true
      modify :starts_at, :utc_datetime, null: true
      modify :location, :text, null: true
      modify :description, :text, null: true

      add :source_external_event_id,
          references(:external_events,
            column: :id,
            name: "events_source_external_event_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:events, [:source_external_event_id],
             name: "events_unique_source_external_event_index"
           )

    create table(:event_participations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :interest, :bigint, null: false
      add :extra_info, :text

      add :space_id,
          references(:spaces,
            column: :id,
            name: "event_participations_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :publication_id,
          references(:event_publications,
            column: :id,
            name: "event_participations_publication_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :membership_id,
          references(:memberships,
            column: :id,
            with: [space_id: :space_id],
            name: "event_participations_membership_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:event_participations, [:space_id, :publication_id, :membership_id],
             name: "event_participations_unique_publication_membership_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :event_participations,
                     [:space_id, :publication_id, :membership_id],
                     name: "event_participations_unique_publication_membership_index"
                   )

    drop constraint(:event_participations, "event_participations_space_id_fkey")

    drop constraint(:event_participations, "event_participations_publication_id_fkey")

    drop constraint(:event_participations, "event_participations_membership_id_fkey")

    drop table(:event_participations)

    drop_if_exists unique_index(:events, [:source_external_event_id],
                     name: "events_unique_source_external_event_index"
                   )

    drop constraint(:events, "events_source_external_event_id_fkey")

    alter table(:events) do
      remove :source_external_event_id
      modify :description, :text, null: false
      modify :location, :text, null: false
      modify :starts_at, :utc_datetime, null: false
      modify :tz, :text, null: false
      modify :title, :text, null: false
    end

    alter table(:external_events) do
      remove :source_missing_at
    end
  end
end
