defmodule Qblog.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pages, primary_key: false) do
      add :author_id, references(:users, column: :id, name: "pages_author_id_fkey", type: :uuid),
        null: false

      add :group_id, references(:groups, column: :id, name: "pages_group_id_fkey", type: :uuid),
        null: false

      add :slug, :text, null: false
      add :title, :text, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `pages` table without the `pages_group_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `pages` table without the `pages_author_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:pages)
  end
end