defmodule Wik.Repo.Migrations.MigrateResources14 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tags) do
      add :primary_block_id,
          references(:blocks,
            column: :id,
            name: "tags_primary_block_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:tags, "tags_primary_block_id_fkey")

    alter table(:tags) do
      remove :primary_block_id
    end
  end
end
