defmodule Qblog.Repo.Migrations.AddProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_user_relation_id,
          references(:group_user_relations,
            column: :id,
            name: "profiles_group_user_relation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:profiles, [:group_user_relation_id],
             name: "profiles_unique_group_user_relation_profile_index"
           )
  end

  def down do
    drop_if_exists unique_index(:profiles, [:group_user_relation_id],
                     name: "profiles_unique_group_user_relation_profile_index"
                   )

    drop constraint(:profiles, "profiles_group_user_relation_id_fkey")

    drop table(:profiles)
  end
end
