defmodule Wik.Repo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:taggings, "taggings_taggable_id_fkey")

    alter table(:taggings) do
      modify :taggable_id,
             references(:group_user_relations,
               column: :id,
               with: [group_id: :group_id],
               name: "taggings_taggable_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:taggings, "taggings_taggable_id_fkey")

    alter table(:taggings) do
      modify :taggable_id,
             references(:group_user_relations,
               column: :id,
               name: "taggings_taggable_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
