defmodule Wik.Repo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:access_grants) do
      add :granted_by_user_id,
          references(:users,
            column: :id,
            name: "access_grants_granted_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:access_google_email_accesses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :email, :text, null: false
      add :membership_type, :text, null: false, default: "member"
      add :revoked_at, :utc_datetime_usec

      add :granted_by_user_id,
          references(:users,
            column: :id,
            name: "access_google_email_accesses_granted_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :revoked_by_user_id,
          references(:users,
            column: :id,
            name: "access_google_email_accesses_revoked_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :source_id,
          references(:access_sources,
            column: :id,
            name: "access_google_email_accesses_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "access_google_email_accesses_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:access_google_email_accesses, [:source_id, :email],
             name: "access_google_email_accesses_unique_source_email_index"
           )

    alter table(:access_external_identities) do
      add :email, :text
    end
  end

  def down do
    alter table(:access_external_identities) do
      remove :email
    end

    drop_if_exists unique_index(:access_google_email_accesses, [:source_id, :email],
                     name: "access_google_email_accesses_unique_source_email_index"
                   )

    drop constraint(
           :access_google_email_accesses,
           "access_google_email_accesses_granted_by_user_id_fkey"
         )

    drop constraint(
           :access_google_email_accesses,
           "access_google_email_accesses_revoked_by_user_id_fkey"
         )

    drop constraint(:access_google_email_accesses, "access_google_email_accesses_source_id_fkey")

    drop constraint(:access_google_email_accesses, "access_google_email_accesses_space_id_fkey")

    drop table(:access_google_email_accesses)

    drop constraint(:access_grants, "access_grants_granted_by_user_id_fkey")

    alter table(:access_grants) do
      remove :granted_by_user_id
    end
  end
end
