defmodule Wik.Repo.Migrations.MigrateResources12 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:event_participations, :event_participations_exactly_one_target,
             check: """
               (publication_id IS NULL) != (external_event_id IS NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:event_participations, :event_participations_exactly_one_target)
  end
end
