defmodule Qblog.Repo.Migrations.Initialize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "user"
      add :email, :citext
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_user_relation_id, :uuid, null: false
    end

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :title, :text, null: false
      add :body, :text, null: false
      add :group_id, :uuid, null: false
      add :author_id, :uuid, null: false
    end

    create table(:pages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id, :uuid, null: false
      add :author_id, :uuid, null: false
    end

    create table(:page_trees, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :nodes, {:array, :map}, null: false
      add :group_id, :uuid, null: false
    end

    create table(:groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:posts) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "posts_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :author_id,
             references(:users,
               column: :id,
               name: "posts_author_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:pages) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "pages_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :author_id,
             references(:users,
               column: :id,
               name: "pages_author_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:page_trees) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "page_trees_group_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:page_trees, [:group_id], name: "page_trees_unique_group_page_tree_index")

    alter table(:groups) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :description, :text

      add :author_id,
          references(:users,
            column: :id,
            name: "groups_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:groups, [:name], name: "groups_unique_name_index")

    create table(:group_user_relations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:profiles) do
      modify :group_user_relation_id,
             references(:group_user_relations,
               column: :id,
               name: "profiles_group_user_relation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:profiles, [:group_user_relation_id],
             name: "profiles_unique_group_user_relation_profile_index"
           )

    alter table(:group_user_relations) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :type, :text, null: false, default: "member"

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_user_relations_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "group_user_relations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:group_user_relations, [:group_id, :user_id],
             name: "group_user_relations_unique_group_user_relation_index"
           )

    create table(:blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :type, :text, null: false
      add :data, :map, null: false, default: %{}

      add :author_id,
          references(:users,
            column: :id,
            name: "blocks_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :owner_group_id,
          references(:groups,
            column: :id,
            name: "blocks_owner_group_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "blocks_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:block_placements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :attachable_id, :uuid, null: false
      add :attachable_type, :text, null: false
      add :order_key, :text, null: false
      add :width, :text, null: false, default: "full"

      add :block_id,
          references(:blocks,
            column: :id,
            name: "block_placements_block_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :group_id,
          references(:groups,
            column: :id,
            name: "block_placements_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:block_placements, [:attachable_type, :attachable_id, :order_key],
             name: "block_placements_unique_attachable_order_key_index"
           )

    create table(:access_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :claimed_at, :utc_datetime_usec
      add :metadata, :map, null: false, default: %{}
      add :provider, :text, null: false
      add :provider_source_id, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :title, :text, null: false

      add :claimed_by_user_id,
          references(:users,
            column: :id,
            name: "access_sources_claimed_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :group_id,
          references(:groups,
            column: :id,
            name: "access_sources_group_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:access_sources, [:provider, :provider_source_id],
             name: "access_sources_unique_provider_source_index"
           )

    create table(:access_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :last_verified_at, :utc_datetime_usec, null: false
      add :status, :text, null: false, default: "active"
      add :external_identity_id, :uuid, null: false
      add :source_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create table(:access_external_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:access_grants) do
      modify :external_identity_id,
             references(:access_external_identities,
               column: :id,
               name: "access_grants_external_identity_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :source_id,
             references(:access_sources,
               column: :id,
               name: "access_grants_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "access_grants_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:access_grants, [:source_id, :user_id],
             name: "access_grants_unique_source_user_index"
           )

    alter table(:access_external_identities) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :avatar_url, :text
      add :display_name, :text
      add :metadata, :map, null: false, default: %{}
      add :provider, :text, null: false
      add :provider_user_id, :text, null: false
      add :username, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "access_external_identities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:access_external_identities, [:provider, :provider_user_id],
             name: "access_external_identities_unique_provider_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:access_external_identities, [:provider, :provider_user_id],
                     name: "access_external_identities_unique_provider_user_index"
                   )

    drop constraint(:access_external_identities, "access_external_identities_user_id_fkey")

    alter table(:access_external_identities) do
      remove :user_id
      remove :username
      remove :provider_user_id
      remove :provider
      remove :metadata
      remove :display_name
      remove :avatar_url
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:access_grants, [:source_id, :user_id],
                     name: "access_grants_unique_source_user_index"
                   )

    drop constraint(:access_grants, "access_grants_external_identity_id_fkey")

    drop constraint(:access_grants, "access_grants_source_id_fkey")

    drop constraint(:access_grants, "access_grants_user_id_fkey")

    alter table(:access_grants) do
      modify :user_id, :uuid
      modify :source_id, :uuid
      modify :external_identity_id, :uuid
    end

    drop table(:access_external_identities)

    drop table(:access_grants)

    drop_if_exists unique_index(:access_sources, [:provider, :provider_source_id],
                     name: "access_sources_unique_provider_source_index"
                   )

    drop constraint(:access_sources, "access_sources_claimed_by_user_id_fkey")

    drop constraint(:access_sources, "access_sources_group_id_fkey")

    drop table(:access_sources)

    drop_if_exists unique_index(:block_placements, [:attachable_type, :attachable_id, :order_key],
                     name: "block_placements_unique_attachable_order_key_index"
                   )

    drop constraint(:block_placements, "block_placements_block_id_fkey")

    drop constraint(:block_placements, "block_placements_group_id_fkey")

    drop table(:block_placements)

    drop constraint(:blocks, "blocks_author_id_fkey")

    drop constraint(:blocks, "blocks_owner_group_id_fkey")

    drop constraint(:blocks, "blocks_owner_user_id_fkey")

    drop table(:blocks)

    drop_if_exists unique_index(:group_user_relations, [:group_id, :user_id],
                     name: "group_user_relations_unique_group_user_relation_index"
                   )

    drop constraint(:group_user_relations, "group_user_relations_group_id_fkey")

    drop constraint(:group_user_relations, "group_user_relations_user_id_fkey")

    alter table(:group_user_relations) do
      remove :user_id
      remove :group_id
      remove :type
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:profiles, [:group_user_relation_id],
                     name: "profiles_unique_group_user_relation_profile_index"
                   )

    drop constraint(:profiles, "profiles_group_user_relation_id_fkey")

    alter table(:profiles) do
      modify :group_user_relation_id, :uuid
    end

    drop table(:group_user_relations)

    drop_if_exists unique_index(:groups, [:name], name: "groups_unique_name_index")

    drop constraint(:groups, "groups_author_id_fkey")

    alter table(:groups) do
      remove :author_id
      remove :description
      remove :name
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:page_trees, [:group_id],
                     name: "page_trees_unique_group_page_tree_index"
                   )

    drop constraint(:page_trees, "page_trees_group_id_fkey")

    alter table(:page_trees) do
      modify :group_id, :uuid
    end

    drop constraint(:pages, "pages_group_id_fkey")

    drop constraint(:pages, "pages_author_id_fkey")

    alter table(:pages) do
      modify :author_id, :uuid
      modify :group_id, :uuid
    end

    drop constraint(:posts, "posts_group_id_fkey")

    drop constraint(:posts, "posts_author_id_fkey")

    alter table(:posts) do
      modify :author_id, :uuid
      modify :group_id, :uuid
    end

    drop table(:groups)

    drop table(:page_trees)

    drop table(:pages)

    drop table(:posts)

    drop table(:profiles)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
