defmodule Qblog.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:block_placements, [:attachable_type, :attachable_id, :order_key],
             name: "block_placements_unique_attachable_order_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:block_placements, [:attachable_type, :attachable_id, :order_key],
                     name: "block_placements_unique_attachable_order_key_index"
                   )
  end
end
