defmodule Wik.Repo.Migrations.AddEventsPhase1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :all_day, :boolean, null: false, default: false
      add :description, :text, null: false
      add :ends_at, :utc_datetime
      add :location_name, :text, null: false
      add :location_text, :text
      add :provenance_policy, :text, null: false, default: "visible"
      add :relay_policy, :text, null: false, default: "internal_only"
      add :starts_at, :utc_datetime, null: false
      add :status, :text, null: false, default: "published"
      add :title, :text, null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "events_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :group_id,
          references(:groups,
            column: :id,
            name: "events_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:event_publications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :publication_type, :text, null: false
      add :relay_note, :text

      add :event_id,
          references(:events,
            column: :id,
            name: "event_publications_event_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :target_group_id,
          references(:groups,
            column: :id,
            name: "event_publications_target_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :published_by_id,
          references(:users,
            column: :id,
            name: "event_publications_published_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:event_publications, [:target_group_id, :event_id],
             name: "event_publications_unique_event_publication_index"
           )
  end

  def down do
    drop_if_exists unique_index(:event_publications, [:target_group_id, :event_id],
                     name: "event_publications_unique_event_publication_index"
                   )

    drop constraint(:event_publications, "event_publications_event_id_fkey")

    drop constraint(:event_publications, "event_publications_target_group_id_fkey")

    drop constraint(:event_publications, "event_publications_published_by_id_fkey")

    drop table(:event_publications)

    drop constraint(:events, "events_author_id_fkey")

    drop constraint(:events, "events_group_id_fkey")

    drop table(:events)
  end
end
