defmodule Qblog.Repo.Migrations.AddBlockPlacementWidth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:block_placements) do
      add :width, :text, null: false, default: "full"
    end
  end

  def down do
    alter table(:block_placements) do
      remove :width
    end
  end
end
