defmodule Wik.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      remove :source_external_event_id
    end

    drop_if_exists unique_index(:events, [:source_external_event_id],
                     name: "events_unique_source_external_event_index"
                   )

    alter table(:event_participations) do
      modify :publication_id, :uuid, null: true

      add :external_event_id,
          references(:external_events,
            column: :id,
            name: "event_participations_external_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:event_participations, [:space_id, :external_event_id, :membership_id],
             name: "event_participations_unique_external_event_membership_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :event_participations,
                     [:space_id, :external_event_id, :membership_id],
                     name: "event_participations_unique_external_event_membership_index"
                   )

    drop constraint(:event_participations, "event_participations_external_event_id_fkey")

    alter table(:event_participations) do
      remove :external_event_id
      modify :publication_id, :uuid, null: false
    end

    create unique_index(:events, [:source_external_event_id],
             name: "events_unique_source_external_event_index"
           )

    alter table(:events) do
      add :source_external_event_id,
          references(:external_events,
            column: :id,
            name: "events_source_external_event_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
