defmodule Wik.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      remove :handled_by_id
    end
  end

  def down do
    alter table(:tickets) do
      add :handled_by_id,
          references(:users,
            column: :id,
            name: "tickets_handled_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
