defmodule Wik.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:external_calendar_subscriptions) do
      remove :cached_calendar_name
      remove :cached_body
      add :cached_name, :text
      add :cached_tz, :text
      add :cached_desc, :text
    end
  end

  def down do
    alter table(:external_calendar_subscriptions) do
      remove :cached_desc
      remove :cached_tz
      remove :cached_name
      add :cached_body, :text
      add :cached_calendar_name, :text
    end
  end
end
