defmodule Qblog.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:blocks) do
      add :author_id,
          references(:users,
            column: :id,
            name: "blocks_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :owner_group_id,
          references(:groups,
            column: :id,
            name: "blocks_owner_group_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :owner_user_id,
          references(:users,
            column: :id,
            name: "blocks_owner_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:blocks, "blocks_author_id_fkey")

    drop constraint(:blocks, "blocks_owner_group_id_fkey")

    drop constraint(:blocks, "blocks_owner_user_id_fkey")

    alter table(:blocks) do
      remove :owner_user_id
      remove :owner_group_id
      remove :author_id
    end
  end
end
