defmodule Qblog.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pages) do
      remove :slug
      remove :title
    end
  end

  def down do
    alter table(:pages) do
      add :title, :text, null: false
      add :slug, :text, null: false
    end
  end
end
