defmodule Wik.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:external_calendar_subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ics_url, :text, null: false

      add :space_id,
          references(:spaces,
            column: :id,
            name: "external_calendar_subscriptions_space_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:external_calendar_subscriptions, [:space_id, :ics_url],
             name: "ext_cal_subs_space_url_idx"
           )
  end

  def down do
    drop_if_exists unique_index(:external_calendar_subscriptions, [:space_id, :ics_url],
                     name: "ext_cal_subs_space_url_idx"
                   )

    drop constraint(
           :external_calendar_subscriptions,
           "external_calendar_subscriptions_space_id_fkey"
         )

    drop table(:external_calendar_subscriptions)
  end
end
