defmodule Wik.Repo.Migrations.CollapseEventLocation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :location, :text
    end

    execute("""
    update events
    set location = trim(
      both ', ' from concat_ws(', ', nullif(location_name, ''), nullif(location_text, ''))
    )
    """)

    execute("""
    update events
    set location = location_name
    where coalesce(location, '') = '' and location_name is not null
    """)

    execute("""
    update events
    set location = 'Unknown location'
    where location is null
    """)

    alter table(:events) do
      modify :location, :text, null: false
      remove :location_text
      remove :location_name
    end
  end

  def down do
    alter table(:events) do
      add :location_name, :text, null: false
      add :location_text, :text
    end

    execute("""
    update events
    set location_name = location,
        location_text = null
    """)

    alter table(:events) do
      remove :location
    end
  end
end
