defmodule Qblog.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:access_telegram_bot_updates) do
      remove :update_type
      add :summary, :map, null: false
    end
  end

  def down do
    alter table(:access_telegram_bot_updates) do
      remove :summary
      add :update_type, :text, null: false
    end
  end
end
