defmodule Wik.Repo.Migrations.AddTickets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :type, :text, null: false
      add :status, :text, null: false, default: "new"
      add :subject, :text, null: false
      add :body, :text, null: false
      add :admin_notes, :text
      add :app_path, :text, null: false
      add :handled_at, :utc_datetime_usec

      add :submitted_by_id,
          references(:users,
            column: :id,
            name: "tickets_submitted_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :handled_by_id,
          references(:users,
            column: :id,
            name: "tickets_handled_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:tickets, "tickets_submitted_by_id_fkey")

    drop constraint(:tickets, "tickets_handled_by_id_fkey")

    drop table(:tickets)
  end
end
